apiVersion: apps/v1
kind: Deployment
metadata:
  name: openhab
  labels:
    app: openhab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: openhab
  template:
    metadata:
      labels:
        app: openhab
    spec:
      containers:
      - name: openhab
        image: openhab/openhab:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        - containerPort: 8443


---
kind: Service
apiVersion: v1
metadata:
  name: openhab
  labels:
    app: openhab
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
    - name: https
      protocol: TCP
      port: 8443
  selector:
    app: openhab

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: openhab
  annotations:
    kubernetes.io/ingress.class: nginx
  rules:
    - host: openhab.k8s.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: openhab
                port:
                  number: 8080