apiVersion: v1
kind: Service
metadata:
  name: {{ include "openhab.fullname" . }}
  labels:
    {{- include "openhab.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port1 }}
      protocol: TCP
      name: http
    - port: {{ .Values.service.port2 }}
      protocol: TCP
      name: https
    - port: {{ .Values.service.port3 }}
      protocol: TCP
      name: console
  selector:
    {{- include "openhab.selectorLabels" . | nindent 4 }}
